### ISSUE TITLE
Unable to get a token

### ISSUE THREAD

**Issue by upsylon44** [FuckingToasters/Fake-Verification-Bot#17]
I updated remoteauthclient and still say this :
```
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<RemoteAuthClient.run() done, defined at C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\remoteauthclient\remoteauthclient.py:196> exception=SessionNotCreatedException('session not created: This version of ChromeDriver only supports Chrome version 106\nCurrent browser version is 102.0.5005.63 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', None, ['Backtrace:', '\tOrdinal0 [0x00CA1ED3+2236115]', '\tOrdinal0 [0x00C392F1+1807089]', '\tOrdinal0 [0x00B466FD+812797]', '\tOrdinal0 [0x00B68C6D+953453]', '\tOrdinal0 [0x00B64200+934400]', '\tOrdinal0 [0x00B619C9+924105]', '\tOrdinal0 [0x00B9806C+1146988]', '\tOrdinal0 [0x00B97A6A+1145450]', '\tOrdinal0 [0x00B918A6+1120422]', '\tOrdinal0 [0x00B6A73D+960317]', '\tOrdinal0 [0x00B6B71F+964383]', '\tGetHandleVerifier [0x00F4E7E2+2743074]', '\tGetHandleVerifier [0x00F408D4+2685972]', '\tGetHandleVerifier [0x00D32BAA+532202]', '\tGetHandleVerifier [0x00D31990+527568]', '\tOrdinal0 [0x00C4080C+1837068]', '\tOrdinal0 [0x00C44CD8+1854680]', '\tOrdinal0 [0x00C44DC5+1854917]', '\tOrdinal0 [0x00C4ED64+1895780]', '\tBaseThreadInitThunk [0x766A00F9+25]', '\tRtlGetAppContainerNamedObjectPath [0x77E87BBE+286]', '\tRtlGetAppContainerNamedObjectPath [0x77E87B8E+238]', ''])>
Traceback (most recent call last):
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\remoteauthclient\remoteauthclient.py", line 199, in run
    await self._task
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\remoteauthclient\remoteauthclient.py", line 181, in _run
    encryptedToken = await self._getToken(p["ticket"])
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\remoteauthclient\remoteauthclient.py", line 138, in _getToken
    captcha_key = await self._event("captcha", captcha_data=j)
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\remoteauthclient\remoteauthclient.py", line 105, in _event
    return await handler(**kwargs)
  File "C:\Users\vicde\Downloads\Fake-Verification-Bot-main\main.py", line 223, in on_captcha
    captcha_key = await solver.solve(custom_params={"rqdata": captcha_data["captcha_rqdata"]})
  File "C:\Users\vicde\Downloads\Fake-Verification-Bot-main\async_hcaptcha\asynchcaptcha.py", line 416, in solve
    "n": await self._getN(),
  File "C:\Users\vicde\Downloads\Fake-Verification-Bot-main\async_hcaptcha\asynchcaptcha.py", line 144, in _getN
    return await self._solve_hsw(d['l'])
  File "C:\Users\vicde\Downloads\Fake-Verification-Bot-main\async_hcaptcha\asynchcaptcha.py", line 183, in _solve_hsw
    return await _hsw_chromedriver()
  File "C:\Users\vicde\Downloads\Fake-Verification-Bot-main\async_hcaptcha\asynchcaptcha.py", line 174, in _hsw_chromedriver
    return await get_event_loop().run_in_executor(ThreadPoolExecutor(4), _hsw)
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\vicde\Downloads\Fake-Verification-Bot-main\async_hcaptcha\asynchcaptcha.py", line 169, in _hsw
    driver = Chrome(service=Service(executable_path=self.args["chromedriver"]), options=options)
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    super().__init__(
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\vicde\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 106
Current browser version is 102.0.5005.63 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00CA1ED3+2236115]
        Ordinal0 [0x00C392F1+1807089]
        Ordinal0 [0x00B466FD+812797]
        Ordinal0 [0x00B68C6D+953453]
        Ordinal0 [0x00B64200+934400]
        Ordinal0 [0x00B619C9+924105]
        Ordinal0 [0x00B9806C+1146988]
        Ordinal0 [0x00B97A6A+1145450]
        Ordinal0 [0x00B918A6+1120422]
        Ordinal0 [0x00B6A73D+960317]
        Ordinal0 [0x00B6B71F+964383]
        GetHandleVerifier [0x00F4E7E2+2743074]
        GetHandleVerifier [0x00F408D4+2685972]
        GetHandleVerifier [0x00D32BAA+532202]
        GetHandleVerifier [0x00D31990+527568]
        Ordinal0 [0x00C4080C+1837068]
        Ordinal0 [0x00C44CD8+1854680]
        Ordinal0 [0x00C44DC5+1854917]
        Ordinal0 [0x00C4ED64+1895780]
        BaseThreadInitThunk [0x766A00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77E87BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77E87B8E+238]
```

Any solution ?

**Comment by FrostedTrash** [comment]
You need to check you Chrome version.
First go into C:\Program Files\Google\Chrome\Application and there is a Folder with only Numbers. In my case this is 110.0.5481.104
![image](https://user-images.githubusercontent.com/109681838/220076895-47d2ae95-cd6c-4af8-9d14-c04d5183e787.png)

This will be different for you.
Now go to https://chromedriver.chromium.org/downloads and download the Chrome driver for your right chrome version.
After Download replace the chromedriver.exe file in the "driver" Folder with the downloaded chromedriver.exe from the website.
