### ISSUE TITLE
JSON decode error when defining database

### ISSUE THREAD

**Issue by mte0** [FuckingToasters/Fake-Verification-Bot#8]
[!] QR Code Generated: https://discord.com/ra/qqFkqrarq0ra0QJ0o-Ky0Jn_8pq0nANPil69y1nVkPo
Task exception was never retrieved
future: <Task finished name='Task-30' coro=<RemoteAuthClient.run() done, defined at /Users/mte/Library/Python/3.8/lib/python/site-packages/remoteauthclient/remoteauthclient.py:196> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/Users/mte/Library/Python/3.8/lib/python/site-packages/remoteauthclient/remoteauthclient.py", line 199, in run
    await self._task
  File "/Users/mte/Library/Python/3.8/lib/python/site-packages/remoteauthclient/remoteauthclient.py", line 179, in _run
    await self._event("userdata", user=user)
  File "/Users/mte/Library/Python/3.8/lib/python/site-packages/remoteauthclient/remoteauthclient.py", line 105, in _event
    return await handler(**kwargs)
  File "/Users/mte/Documents/coding/discord-hackering/Fake-Verification-Bot-main/main.py", line 206, in on_userdata
    database = json.load(open("/Users/mte/Documents/coding/discord-hackering/Fake-Verification-Bot-main/databae.json", encoding="utf-8"))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mte0** [comment]
nvm, i am the stupid, simply add `{}` in the blank `database.json` file.
